### ISSUE TITLE
HRIM command line tool

### ISSUE THREAD

**Issue by LanderU** [AcutronicRobotics/HRIM#27]
**Describe the feature that you would like to include:**
I would like to have a `hrim` command line tool. I will start working on it and I'll create a PR to be verified.

**Additional context**
NONE

**Comment by vmayoral** [comment]
+1 for this. @ibaiape?

**Comment by vmayoral** [comment]
maybe @LanderU, you'd like to work on it?

**Comment by ibaiape** [comment]
I see it as a very welcomed quality-of-life (am I using that term right?) improvement.

Anything you'd need @LanderU, tell me. I'm personally curious to see how the process for this works and I'd be happy to help.

**Comment by LanderU** [comment]
WIP on: https://github.com/erlerobot/HRIM/tree/installator

I'll fix the setup.py for Pypi and is ready. @vmayoral, under Acutronic Robotics or under Erle Robotics?

**Comment by LanderU** [comment]
This is ready for review. I would like to know some details before uploading to Pypi.  Main question is on the previous comment:

> @vmayoral, under Acutronic Robotics or under Erle Robotics?

**Comment by LanderU** [comment]
https://github.com/erlerobot/HRIM/pull/46

**Comment by LanderU** [comment]
Done!
