### ISSUE TITLE
Error compiling hrim_qa

### ISSUE THREAD

**Issue by igorrecioh** [AcutronicRobotics/HRIM#87]
**Describe the bug**
When compiling HRIM I get following error in hrim_qa package:
```bash
Starting >>> hrim_qa
--- stderr: hrim_qa                           
CMake Error at CMakeLists.txt:29 (SUBDIRLIST):
  SUBDIRLIST Macro invoked with incorrect arguments for macro named:
  SUBDIRLIST


---
Failed   <<< hrim_qa	[ Exited with code 1 ]
```

**To Reproduce**
- Follow ROS2 installation instructions from sources (Dashing)
- Clone HRIM repo in src folder and generate the models
- colcon build --symlink-install --merge-install

**Expected behavior**
- I expected to compile whole ws without errors

**Comment by LanderU** [comment]
Remove `--symlink-install` from your compilation.

**Comment by ahcorde** [comment]
you need to add `-DHRIM_DIRECTORY`

**Comment by LanderU** [comment]
Checkout how were are compiling on travis:

* https://github.com/AcutronicRobotics/HRIM/blob/master/.docker/ci/docker-entrypoint.sh#L97

**Comment by igorrecioh** [comment]
Working now! Used this:
```bash
colcon build --merge-install --packages-select hrim_qa --cmake-args -DHRIM_DIRECTORY=/home/erle/ros2_ws/src/HRIM/generated/
```
